operantnetworks/ndn-ind

CHANGELOG
include/ndn-ind/encrypt/encryptor-v2.hpp
src/encrypt/decryptor-v2.cpp
src/encrypt/encryptor-v2.cpp

On pull request #9, we added support for secured Interest and GCK, but we didn't update the CHANGELOG. Also, when porting to JavaScript, I found some minor errors in the C++ code.
This pull request has five small commits. The first commit fixes an error message for decrypting an Interest.
The second commit corrects the internal method `DecryptorV2::fetchGck` to behave like `fetchCk` by clearing the pendingInterest ID as soon as a Data packet is received (and not wait for it to be validated).
The third commit fixes the spelling of the API method `EncryptorV2::setcheckForNewGckInterval` to `setCheckForNewGckInterval` . (These is a convenience method to override a default. No example code currently calls it, so no other code needs to be changed.)
The fourth commit fixes a bug in …

CHANGELOG for secured interest + minor fixes

---

CHANGELOG
examples/test-access-manager.cpp
examples/test-echo-consumer.cpp
examples/test-publish-async-nfd.cpp
examples/test-secured-interest-responder.cpp
examples/test-secured-interest-sender.cpp

This pull request updates the most commonly-used example programs with optional command-line arguments. Following are the help message for each.
Usage: test-echo-consumer [options]
-n name-prefix  If omitted, use /testecho
-h host         If omitted or "", the default Face connects to the local forwarder
-p port         If omitted, use 6363
-?              Print this help
Usage: test-publish-async-nfd [options]
-n name-prefix  If omitted, use /testecho
-k              Keep responding. If omitted, quit after one response
-?              Print this help
Usage: test-access-manager [options]
-d dataset                 The dataset part of the access group name. If omitted, use /test-group
-i access-manager-identity The access manager identity name. This must be an identity on the system.
If …

examples: Add optional command-line arguments

---

contrib/murmur-hash/murmur-hash.c
src/c/util/ndn_memory.c
src/encoding/oid.cpp
src/interest.cpp
src/security/v2/validation-policy-config.cpp
src/security/v2/validator-config/config-checker.cpp
src/security/v2/validator-config/config-filter.cpp
src/security/v2/validator-config/config-rule.cpp
src/sync/detail/invertible-bloom-lookup-table.cpp
src/sync/digest-tree.cpp
src/util/boost-info-parser.hpp
src/util/regex/ndn-regex-matcher-base.cpp

The recent CodeDX scan had High, Medium and Low severity findings. This pull request addresses the High and Medium findings. It has three commits:
- High: "Returning object that will be invalid when returning". Update BoostInfoTree::getFirstValue so that it return a null pointer or a shared_ptr with a copy of the string.
- Medium: "Prefix ++/-- operators should be preferred for non-primitive types". Change all for loops to use prefix increment.
- Medium: "Improper Restriction of Operations within the Bounds of a Memory Buffer". Updated Interest::toUri() to only call write if starting the write from bytes before the end of the buffer.

CodeDX findings (High and Medium)

---

CHANGELOG
Makefile.am
Makefile.in
examples/cert-install.cpp

In examples, add the cert-install program which shows how to install a single certificate from a file into the local security database.

examples: Add cert-install.

---

include/ndn-ind/encoding/tlv-wire-format.hpp

Starting with version 0.7.0, NFD drops support for TVL packet formats earlier than v0.3. For example, it will reject a request to register a prefix using the older format. So, this pull request changes the library's default wire encoding to v0.3.

encoding: Change the default TlvWireFormat to v0.3.

---

CHANGELOG
examples/test-access-manager.cpp
examples/test-secured-interest-responder.cpp
examples/test-secured-interest-sender.cpp
include/ndn-ind/encrypt/decryptor-v2.hpp
include/ndn-ind/encrypt/encryptor-v2.hpp
src/encrypt/decryptor-v2.cpp
src/encrypt/encryptor-v2.cpp
tests/unit-tests/test-encryptor-v2.cpp

This pull request updates `EncryptorV2` to support fetching the GCK from multiple access managers in a prioritized list. If a higher-priority access managers does not respond, then use the next responding access manager on the list. (If the `EncrpytorV2` is created with only one access manager, then the behavior is unchanged.)
This pull request has six commits. The first commit is a minor correction to `EncryptorV2`. The private method `decryptGckAndProcessPendingDecrypts` should be named `decryptGckAndProcessPendingEncrypts`.
The second commit re-arranges code in `EncryptorV2`, keeping the same functionality. We create an inner class `KeyManager` which keeps the details of fetching the content key for a particular access manager. The main class adds a list of `keyManagers_` which …

Multiple access prefixes

---

src/security/certificate/certificate.cpp
src/transport/async-socket-transport.hpp
src/util/regex/ndn-regex-backref-matcher.hpp
src/util/regex/ndn-regex-component-matcher.hpp
src/util/regex/ndn-regex-component-set-matcher.hpp
src/util/regex/ndn-regex-matcher-base.hpp
src/util/regex/ndn-regex-pattern-list-matcher.hpp
src/util/regex/ndn-regex-pseudo-matcher.hpp
src/util/regex/ndn-regex-repeat-matcher.hpp
src/util/regex/ndn-regex-top-matcher.cpp
src/util/regex/ndn-regex-top-matcher.hpp

This pull request resolves 9 medium-severity security findings in a code scan. This pull request has 4 commits.
The first commit resolves 2 findings for "All member variables are called consecutively in the order the variables are declared" by setting `primaryBackrefManager_` and `secondaryBackrefManager_` in the constructor's initialization list instead of the body of the constructor.
The second commit resolves 5 findings for "Virtual function is called from constructor". The base class `NdnRegexMatcherBase` declares the pure virtual method `compile`. The derived classes override it, but also call it from the constructor which can have undefined initialization. This code was imported as-is from ndn-cxx. It appears that the method `compile` does not need to be virtual. So this commit …

Resolve security scan findings

---

include/ndn-ind/util/blob.hpp

In Blob, specify the assignment operator to get rid of compiler warnings.
Blob& operator=(const Blob& blob) = default;

In Blob, add the default assignment operator

---

include/ndn-ind/generic-signature.hpp

In GenericSignature, the class variables `typeCode_` and `changeCount_` are [declared in that order](https://github.com/operantnetworks/ndn-ind/blob/2047f62f85e9580767b712a487154fa131375a8c/include/ndn-ind/generic-signature.hpp#L155-L156). But in the constructor, they are initialized in the reverse order, and some compilers issue a warning. This pull request updates the constructor to initialize in the same order as declared.

GenericSignature: In the constructor, put initializers in the same order as declared

---

include/ndn-ind/digest-sha256-signature.hpp
include/ndn-ind/generic-signature.hpp
src/c/encoding/tlv/tlv-signature-info.c
src/digest-sha256-signature.cpp
src/generic-signature.cpp
src/security/validity-period.cpp

This pull request has two commits. The first commit adds ValidityPeriod to `DigestSha256Signature` and `GenericSignature`, including the "getter" and "setter" method. For `DigestSha256Signature`,  the low-level tlv-signature-info.c is also updated to encode and decode the validity period in the TLV DigestSha256 signature info.
The second commit updates the `DigestSha256Signature` methods `get` and `set` which transfer fields between the C++ managed-memory object`DigestSha256Signature` and the non-managed-memory `SignatureLite` struct which is used by the low-level TLV encoder. The validity period fields must also be transferred. This commit also updates the `DigestSha256Signature` method `getChangeCount` to mark the object as changed if its `ValidityPeriod` is changed. (A change means …

Add ValidityPeriod to DigestSha256Signature and GenericSignature

---

CHANGELOG
Makefile.am
Makefile.in
VisualStudio/ndn-ind/ndn-ind.vcxproj
VisualStudio/ndn-ind/ndn-ind.vcxproj.filters
include/Makefile.am
include/Makefile.in
include/ndn-ind-tools/micro-forwarder/micro-forwarder-transport.hpp
include/ndn-ind-tools/micro-forwarder/micro-forwarder.hpp
include/ndn-ind/lite/encoding/element-listener-lite.hpp
include/ndn-ind/lite/encoding/element-reader-lite.hpp
include/ndn-ind/lite/util/dynamic-uint8-array-lite.hpp
src/lite/encoding/element-reader-lite.cpp
tools/micro-forwarder/micro-forwarder-transport.cpp
tools/micro-forwarder/micro-forwarder.cpp

A MicroForwarder is an in-memory object with a PIT and a FIB and functionality similar to a full NDN forwarder. The application can create a Face to the MicroForwarder instead of a normal forwarder. (This is useful on systems that don't support NFD.) The application can create forwarder faces and routes.
This pull request has three commits. The first commit adds the `ElementListenerLite` class which exposes existing functionality in the public API so that it can be used by the MicroForwarder.
The second commit adds the `MicroForwarder` to the ndn-ind-tools library (which is always compiled and installed along with the main ndn-ind library).  It also adds the class `MicroForwarderTransport`. When the application creates a Face, it uses this to connect to the MicroForwarder.
The third …

Add MicroForwarder

---

include/ndn-ind/security/v2/trust-anchor-group.hpp
src/security/v2/trust-anchor-group.cpp

The NDN validator uses a `TrustAnchorGroup` to load the certificate chain trust anchor certificates. This pull request updates the code to only load a trust anchor certificate if the current time falls within the certificate's validity period. This includes "Static" trust anchors (added from a config file or in a method call by the application) and "Dynamic" trust anchors (loaded from a trust anchor directory).

In TrustAnchorGroup, don't load a trust anchor certificate outside its validity period

---

include/ndn-ind-tools/micro-forwarder/micro-forwarder-transport.hpp
include/ndn-ind-tools/micro-forwarder/micro-forwarder.hpp
tools/micro-forwarder/micro-forwarder-transport.cpp
tools/micro-forwarder/micro-forwarder.cpp

This is a follow-on to pull request #31 for the MicroForwarder. Currently, the application can configure the MicroForwarder with a route to another host and send an Interest. But the application cannot receive Interests. Our use case is where the application node does not have a public IP address. So, to receive interests from a remote node, we need to do a "remote prefix registration" with the NFD on the remote node.
This pull request has five commits. The first commit updates the MicroForwarder to rename the method `registerRoute` to `addRoute` since this operation is close to `nfdc add route` and we don't want to confuse it with prefix registration.
The second commit internally updates `MicroForwarderConnection` to make `MicroForwarder` a friend class and to add the variable …

MicroForwarder: Support remote and local register prefix

---

VisualStudio/ndn-ind/ndn-ind.vcxproj
VisualStudio/ndn-ind/ndn-ind.vcxproj.filters
include/ndn-ind-tools/micro-forwarder/micro-forwarder-transport.hpp
include/ndn-ind/transport/async-tcp-transport.hpp
include/ndn-ind/transport/async-unix-transport.hpp
include/ndn-ind/transport/tcp-transport.hpp
include/ndn-ind/transport/transport.hpp
include/ndn-ind/transport/udp-transport.hpp
include/ndn-ind/transport/unix-transport.hpp

This is a follow-on to pull request #17 for Windows support. As explained there, classes need to be declared with `ndn_ind_dll`. But inner classes need it to. I found most places, but a few were missing which are the inner `ConnectionInfo` class of the Transport classes.
The second commit adds x509-certificate-info.cpp to the VisualStudio project (which should have been added in the pull request for X.509 support).

In the Transport classes, the inner ConnectionInfo class also needs ndn_ind_dll

---

include/ndn-ind/security/certificate/x509-certificate-info.hpp
src/encoding/der/der-node.cpp
src/encoding/der/der-node.hpp
src/security/certificate/x509-certificate-info.cpp

This is a follow-on to pull request #35 to support an NDN name placed in the X.509 certificate's extensions as a URI field in the Subject Alternative Names.
This pull request has two commits. The first commit updates the `DerNode` encoder/decoder with the support class `DerImplicitByteString` . This is needed because the URI field is encoded with an IMPLICIT type.
The second commit updates the class `X509CertificateInfo` so that the utility methods [makeName](https://github.com/operantnetworks/ndn-ind/blob/b00eb477e22b91fec30dac94e7c26c818fb6d9de/include/ndn-ind/security/certificate/x509-certificate-info.hpp#L116-L128) and [makeX509Name](https://github.com/operantnetworks/ndn-ind/blob/b00eb477e22b91fec30dac94e7c26c818fb6d9de/include/ndn-ind/security/certificate/x509-certificate-info.hpp#L1 …

Support NDN name in X.509 certificate Subject Alternative Names

---

src/encrypt/encryptor-v2.cpp

When a remote key manager goes offline, EncryptorV2 sets isKeyReady to false for the related internal `KeyManager`. When we encrypt, there is already logic to check if the first content key has been retrieved. But we need extra to check isKeyReady each time before using a content key to encrypt.

In EncryptorV2, check again for isKeyReady

---

include/ndn-ind-tools/micro-forwarder/micro-forwarder.hpp
tools/micro-forwarder/micro-forwarder.cpp

This is a stability update for the MicroForwarder. If the link for a face is down, then send may cause an error. This pull request catches and logs errors, but lets the MicroForwarder continue functioning.

MicroForwarder: Catch and log errors in transport send

---

tools/micro-forwarder/micro-forwarder.cpp

When the MicroForwarder receives an interest, it creates a PIT entry with a timeout. If it receives a duplicate interest with the same name (but different nonce), it "aggregates" into the PIT entry but updating the PIT entry's timeout and continues to wait for the response Data packet. In this case, the MicroForwarder currently does not forward the duplicate Interest. This is an optimization and is not strictly necessary since the system will still function if a duplicate Interest is forwarded. It makes sense if the response Data packet is received.
But if the response Data packet is not received (because the responder is not responding) then there can be a problem if the application keeps re-sending the timed-out interests but the MicroForwarder sees it as a duplicate and doesn't forward …

In the MicroForwarder, allow re-forwarding a duplicate interest

---

include/ndn-ind/encrypt/encryptor-v2.hpp
src/encrypt/encryptor-v2.cpp

EncryptorV2 keeps a list of key managers and periodically check if they are responding. If one doesn't respond, EncryptorV2 switches to the next one in the list. But this logic didn't consider what to do if no key manager is responding. Currently, it will add to the pending encryption queue, waiting for a key manager to start responding. But this could last a very long time and is not the intended behavior. (If the application depends on the result of an encrypt operation, it can appear to freeze as each encrypt operation is added to the queue.)
This pull request updates EncryptorV2 as follows: On each successful encrypt operation, it sets `iKeyManagerLastEncryption_` to the index in the list of key managers. If all key managers stop responding, continue encrypting using the content key …

In EncryptorV2, if no access managers respond, use the one from the last encryption. 

---

src/face.cpp

The default Face constructor is for connecting to the local NFD using Unix sockets. Windows and other systems without unistd.h can't do this. In this case, the library simply doesn't compile the default Face constructor. If an example has this as an option, then the example will have a linker failure. This pull request changes this case to compile the default Face constructor, but to throw an exception. Therefore, the examples will compile and link.

Face: If no unistd.h, compile the default constructor with exception

---

include/ndn-ind/security/certificate/x509-certificate-info.hpp
include/ndn-ind/security/v2/certificate-v2.hpp
src/security/certificate/x509-certificate-info.cpp

This pull request has two commits. In the first commit, in `X509CertificateInfo` check the extensions for an X509v3 CRL Distribution Points extension with the URI. Add the method `getCrlDistributionUri`. In `CertificateV2` also add the helper method `getCrlDistributionUri` to get the CRL URI from the encapsulated `X509CertificateInfo`, if present.
In the second commit, in `X509CertificateInfo` add the method `getSerialNumber`. In `CertificateV2` also add the helper method `getX509SerialNumber` to get the serial number from the encapsulated `X509CertificateInfo`, if present.

X509CertificateInfo: Add getCrlDistributionUri

---

include/ndn-ind/util/logging.hpp

If log4cxx is installed and enabled, then ndn-ind uses it for log output. If not, then it uses the second part of logging.hpp . Currently, it only prints log messages if `_DEBUG` is defined, but we also want the option if the library is not compiled in the debug configuration.
This pull request changes logging.hpp to also print log messages if `NDN_IND_WITH_LOGGING` is defined. It also uses the macro for `_LOG_DEBUG` for printing all log levels (not just DEBUG and ERROR).

For non-log4cxx, allow NDN_IND_WITH_LOGGING. Use for all log levels

---

src/node.cpp

This is a small pull request to improve the log output error message for register prefix failure to include the prefix name.

Clarify log output for RegisterResponse failure

---

VisualStudio/ndn-ind/ndn-ind.vcxproj
VisualStudio/ndn-ind/ndn-ind.vcxproj.filters
include/ndn-ind/security/v2/certificate-storage.hpp
include/ndn-ind/security/v2/validation-state.hpp
include/ndn-ind/security/v2/validator.hpp
src/security/v2/certificate-storage.cpp
src/security/v2/validation-state.cpp
src/security/v2/validator.cpp
src/security/v2/x509-crl-fetcher.cpp

This is a follow-on to pull request #48 which updates the Validator to use the CRL to check if a fetched certificate is revoked. But there is another case where the packet given to the `validate` method is a certificate (instead of an Interest or a normal Data packet). This certificate should also be checked for revocation.
This pull request has three commits. The first commit changes `CertificateStorage::findRevokedCertificate` from a static method to a member method of `CertificateStorage` so that it can access the CRL when it is called by `verifyOriginalPacket`.
The second commit updates the virtual method `ValidationState::verifyOriginalPacket` to add the parameter `certificateStorage`. If the original packet is a certificate ,then `DataValidationState::verifyOriginalPacket` calls …

In validate, check the CRL if the packet is a certificate

---

include/ndn-ind/encrypt/encryptor-v2.hpp
src/encrypt/encryptor-v2.cpp

The `EncryptorV2` method `checkForNewGck`  periodically sends a “GCK _latest” interest to the access manager to check if there is a new group content key. 
https://github.com/operantnetworks/ndn-ind/blob/2ab49d4749447d5319ac1ccce3e6f3088c8c1de3/src/encrypt/encryptor-v2.cpp#L802 
Currently, this Interest has the default lifetime (4 seconds). But on a heavily-loaded system, it may take longer for the access manager to respond. This pull request updates `EncryptorV2` to add the method `setGckLatestInterestLifetime` so that this is configurable.

In EncryptorV2, add setGckLatestInterestLifetime

---

include/ndn-ind/security/v2/certificate-cache-v2.hpp
include/ndn-ind/security/v2/x509-crl-cache.hpp
src/security/v2/certificate-cache-v2.cpp
src/security/v2/x509-crl-cache.cpp

`CertificateCacheV2` and `X509CrlCache`, the `clear` method is defined inline in the public API. It uses `max()` which could conflict with an application which includes a header file with a different definition of `max()`. This pull request moves the definition of the `clear` method into the cpp file to avoid a conflict in the public API.

CertificateCacheV2 and X509CrlCache: Move clear() into the cpp file

---

include/ndn-ind/security/v2/validation-error.hpp
src/security/v2/validation-error.cpp

`ValidationError` defines several constants including `NO_ERROR`. This can conflict with winerror.h on Windows which has a `#define` for `NO_ERROR`. This pull request renames it to `NO_VALIDATION_ERROR` to avoid conflict in a Windows application which also includes winerror.h . This should have minimal impact: Normally an NDN application does not use `ValidationError` constants directly, but uses the error string output. Also, an application normally would not check for the "no error" condition but would only check error constants if there was an error.

ValidationError: Rename NO_ERROR to NO_VALIDATION_ERROR

---

src/security/v2/trust-anchor-group.cpp

The certificate Validator loads certificates from the trust anchors directory. For TRACE debugging, it would be useful to see the file and certificate names. This pull request updates the `loadCertificate` method to log the filename and certificate name of the loaded certificate (or a message if cannot parse the file).

In loadCertificate, log the certificate names that are loaded

---

examples/cert-install.cpp

Most example applications check the config options to make sure the needed dependencies are installed. For example, test-chrono-chat relies on Protobuf, so [it checks for it](https://github.com/operantnetworks/ndn-ind/blob/240a7d4caf785b1656a7df3a51d5451bb93073bc/examples/test-chrono-chat.cpp#L35-L37). The cert-install example program has a dependency on Sqlite3, so this pull request adds a check for it, so that make will succeed if the dependency is not installed.

Only compile cert-install if NDN_IND_HAVE_SQLITE3

---

include/ndn-ind/transport/tcp-transport.hpp
src/c/transport/socket-transport.h
src/c/transport/tcp-transport.h
src/transport/tcp-transport.cpp

The existing way to create a TCP face is to supply a connection info with a host:
Face face(
ptr_lib::make_shared<TcpTransport>(), 
ptr_lib::make_shared<TcpTransport::ConnectionInfo>("1.2.3.4")));
But the application may have an already-open socket descriptor, for example from a new incoming connection. This pull request adds a `TcpTransport::ConnectionInfo` constructor to supply an already-open socket descriptor:
int socketDescriptor = myCodeToOpenASocket();
Face face(
ptr_lib::make_shared<TcpTransport>(), 
ptr_lib::make_shared<TcpTransport::ConnectionInfo>(socketDescriptor)));

TcpTransport: Support a ConnectionInfo with an already-open socket

---

include/ndn-ind/util/logging.hpp

This pull request fixes a typo in pull request #47 . The conditions for using non-log4cxx logging statements is:
#if 1 || defined(_DEBUG) || defined(NDN_IND_WITH_LOGGING)
The `1 ||` makes this condition always true. It is a typo left over from testing. This pull request removes it.

logging.hpp: Fix typo for non-log4cxx conditions

---

include/ndn-ind/security/certificate/x509-certificate-info.hpp
src/security/certificate/x509-certificate-info.cpp

This function takes a common name and produces a Blob with the
common name in the X509 name format.

Add X509CertificateInfo::makeX509NameOfCommonName()
